#! /usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path '../', __FILE__

# This is a handy manual verification that oauth is happening with Twitter
# and credentials is properly set up

require 'yaml'
require 'twitter_tag_tracker'

creds = YAML.load_file('credentials.yml')
ttt = TwitterTagTracker.new(creds)
ttt.each_tag {|tag| puts tag}
