#! /usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path '../', __FILE__
require 'yaml'
require 'twitter_tag_tracker'
require 'tweet_top_ten'

credentials_filename = './credentials.yml'

unless File.exist?(credentials_filename)
  puts """
  No credentials.yml file found in current directory.
  Please copy credentials_sample.yml to credentials.yml and enter the oauth credentials.
  It would be bad security practice had I left mine in there.

  You may also use man_tag_stream to verify the credentials are working with twitter.
  """
  exit!
end

streamer = TwitterTagTracker.new(YAML.load_file(credentials_filename))

TweetTopTen.new(streamer, 8080).start
